#!/bin/bash

java -Dwebdriver.gecko.driver="geckodriver" -jar selenium-server-standalone.jar -role node -nodeConfig nodeconfig.json -hub http://127.0.0.1:4444/grid/register -browser "browserName=firefox,platform=MAC" -port 5556 