#!/bin/bash

java -Dwebdriver.chrome.driver="chromedriver" -jar selenium-server-standalone.jar -role node -hub http://127.0.0.1:4444/grid/register -browser "browserName=chrome,platform=MAC" -port 5555 